services:
  ticket-database:
    image: postgres:alpine
    container_name: ticket-database
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always

  ticket-cache:
    image: redis
    container_name: ticket-cache
    ports:
      - 6379:6379
