services:
  ticket-database:
    image: postgres:alpine
    container_name: ticket-database
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always

  last-actions-mongodb:
    image: mongo
    container_name: last-actions-database
    ports:
      - 27017:27017
    restart: always
